# To create this environment, run:
# conda env create -f environment.yml
#
# To update this environment, run:
# conda env update -f environment.yml
#
# To activate this environment, run:
# conda activate nhl-display-board

name: nhl-display-board

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - pandas
  - pandas-stubs
  - requests
  - matplotlib
  - seaborn
  - streamlit
  - pip
  - pip:
    - nhl-api-py

