# To create this environment, run:
# conda env create -f local-dev/environment.yml
#
# To update this environment, run:
# conda env update -f local-dev/environment.yml
#
# To activate this environment, run:
# conda activate nhl-display-board

name: nhl-display-board

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - pandas>=2.3
  - pandas-stubs>=2.3
  - streamlit
  - pip
  - pip:
    - nhl-api-py==3.0.2
